project_id = "vnbygqpkgtrdzidkyapa"

[functions.get-employees]
verify_jwt = false

[functions.get-seats] 
verify_jwt = false

[functions.generate-schedule]
verify_jwt = false

[functions.analytics-engine]
verify_jwt = false

[functions.realtime-monitor]
verify_jwt = false